### LOCAL

### Get the message: Hello World!
GET http://localhost:3000/

### Get all the users
GET http://localhost:3000/users

### Get user by ID
GET http://localhost:3000/users/66feda6634acaf25fc843242

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test4@test.com",
  "username": "test4@test.com",
  "name": "Hello6",
  "ipaddress": "94.121.16.56"
}

### Update user
PUT http://localhost:3000/users/68836bd51efcd0472451f52a
Content-Type: application/json

{
  "email": "test1@test.com",
  "username": "test1@test.com",
  "name": "Hello1",
  "ipaddress": "94.121.16.01"
}

### Delete user
DELETE http://localhost:3000/users/68835d7d2cb32be7339ea911
Content-Type: application/json


### RENDER ////////////////////////////////////////////////////////////////////////////////////////////////

### Get the message: Hello World!
GET https://cse-341-project1-7a6g.onrender.com

### Get all the users
GET https://cse-341-project1-7a6g.onrender.com/users

### Get user by ID
GET https://cse-341-project1-7a6g.onrender.com/users/66feda6634acaf25fc843242

### Create a new user
POST https://cse-341-project1-7a6g.onrender.com/users
Content-Type: application/json

{
  "email": "test20@test.com",
  "username": "test20@test.com",
  "name": "Hello20",
  "ipaddress": "94.121.16.020"
}

### Update user
PUT https://cse-341-project1-7a6g.onrender.com/users/688364cb97caedafe2c331eb
Content-Type: application/json

{
  "email": "test21*@test.com",
  "username": "test21*@test.com",
  "name": "Hello21*",
  "ipaddress": "94.121.16.021*"
}

### Delete user
DELETE https://cse-341-project1-7a6g.onrender.com/users/68803610add67c9e0294ae79
Content-Type: application/json
